animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']

print "1. The animal at 1 =", animals[1]
print "2. The third (3rd) animal =", animals[2]
print "3. The first (1st) animal =", animals[0]
print "4. The animal at 3 =", animals[3]
print "5. The fifth (5th) animal =", animals[4]
print "6. The animal at 2 =", animals[2]
print "7. The sixth (6th) animal =", animals[5]
print "8. The animal at 4 =", animals[4]
